const PAGES={
 dashboard:{title:'Dashboard',sub:'Your MAVNARO beta command center.',file:'index.html'},
 chat:{title:'Chat & Earn',sub:'Talk, explore, and discover surprise rewards.',file:'chat.html'},
 spin:{title:'Spin',sub:'Take your daily chance at a random reward.',file:'spin.html'},
 missions:{title:'Missions',sub:'Complete simple activities and build your score.',file:'missions.html'},
 referral:{title:'Referral',sub:'Invite people and earn when your network grows.',file:'referral.html'},
 leaderboard:{title:'Leaderboard',sub:'See who is making the most of the beta.',file:'leaderboard.html'},
 profile:{title:'Profile',sub:'Your beta identity and activity.',file:'profile.html'}
};
const key='mavnaro_beta_v1';
function state(){let s=JSON.parse(localStorage.getItem(key)||'null');if(!s){s={balance:0,xp:120,level:1,spins:1,referrals:0,chats:0,missions:0,streak:1,joined:Date.now(),history:[],completed:{}};save(s)}return s}
function save(s){localStorage.setItem(key,JSON.stringify(s))}
function addReward(amount,type){const s=state();s.balance+=amount;s.xp+=Math.max(1,Math.floor(amount/2));s.level=1+Math.floor(s.xp/250);s.history.unshift({amount,type,time:Date.now()});s.history=s.history.slice(0,20);save(s);return s}
function shell(page,content){document.getElementById('app').innerHTML=`<aside class="sidebar"><a class="brand" href="index.html"><img src="assets/logo.png"><span>MAVNARO</span></a><nav>${Object.entries(PAGES).map(([k,p])=>`<a class="nav ${k===page?'active':''}" href="${p.file}"><span>${icons[k]||'◈'}</span>${p.title}</a>`).join('')}</nav><div class="beta"><b>FREE BETA</b><small>NFT access is OFF during testing.</small></div></aside><main><header><div><div class="eyebrow">MAVNARO / BETA</div><h1>${PAGES[page].title}</h1><p>${PAGES[page].sub}</p></div><div class="wallet"><span class="dot"></span> Beta Wallet <b>${state().balance}</b></div></header><section>${content}</section></main>`}
const icons={dashboard:'⌂',chat:'✦',spin:'◉',missions:'◆',referral:'↗',leaderboard:'♛',profile:'◎'};
function cards(){const s=state();return `<div class="grid stats"><div class="card stat"><small>BETA BALANCE</small><strong>${s.balance.toLocaleString()}</strong><span>MAVNARO</span></div><div class="card stat"><small>XP</small><strong>${s.xp}</strong><span>Level ${s.level}</span></div><div class="card stat"><small>REFERRALS</small><strong>${s.referrals}</strong><span>friends joined</span></div><div class="card stat"><small>SPINS</small><strong>${s.spins}</strong><span>available today</span></div></div>`}
function dashboard(){const s=state();shell('dashboard',`${cards()}<div class="hero"><div><span class="pill">SEASON 0 · FREE BETA</span><h2>Enter the experiment.</h2><p>MAVNARO is a social reward playground. Chat, spin, complete missions and invite friends. Everything is free while we test the economy.</p><div class="actions"><a class="btn primary" href="chat.html">Start chatting</a><a class="btn" href="spin.html">Try your spin</a></div></div><img src="assets/cover.png"></div><div class="grid two"><div class="card"><div class="cardhead"><h3>Recent rewards</h3><a href="profile.html">View all</a></div>${s.history.length?s.history.slice(0,5).map(x=>`<div class="row"><span>${x.type}</span><b>+${x.amount}</b></div>`).join(''):'<div class="empty">No rewards yet. Your first one is waiting.</div>'}</div><div class="card"><div class="cardhead"><h3>How it works</h3></div><div class="steps"><div><b>01</b><span>Interact</span></div><div><b>02</b><span>Play</span></div><div><b>03</b><span>Earn</span></div><div><b>04</b><span>Invite</span></div></div></div></div>`)}
function chat(){shell('chat',`<div class="chatwrap card"><div class="chatlog" id="chatlog"><div class="bubble bot"><span class="avatar">M</span><div><b>MAVNARO</b><p>Welcome to the beta. Say something interesting. A good conversation may trigger a surprise reward.</p></div></div></div><div class="composer"><input id="chatinput" placeholder="Start a conversation…" maxlength="240"><button class="btn primary" id="send">Send</button></div><small class="hint">Beta scoring is experimental. Rewards are simulated and may reset.</small></div>`);document.getElementById('send').onclick=sendChat;document.getElementById('chatinput').onkeydown=e=>{if(e.key==='Enter')sendChat()}}
function sendChat(){const input=document.getElementById('chatinput');const text=input.value.trim();if(!text)return;const log=document.getElementById('chatlog');log.insertAdjacentHTML('beforeend',`<div class="bubble user"><div><p>${escapeHtml(text)}</p></div></div>`);input.value='';const replies=['Interesting. Tell me what you would build if you had unlimited users.','That has potential. What would make someone return tomorrow?','MAVNARO noticed that one. Keep going.','Now we are getting somewhere. Try a more unusual idea.'];setTimeout(()=>{const reward=Math.random()<.55?[5,8,12,20][Math.floor(Math.random()*4)]:0;let reply=replies[Math.floor(Math.random()*replies.length)];if(reward){addReward(reward,'Chat reward');reply+=` ✦ Surprise: +${reward} MAVNARO.`}log.insertAdjacentHTML('beforeend',`<div class="bubble bot"><span class="avatar">M</span><div><b>MAVNARO</b><p>${reply}</p></div></div>`);log.scrollTop=log.scrollHeight},350)}
function spin(){const s=state();shell('spin',`<div class="spinpage"><div class="card wheelcard"><div class="wheel" id="wheel"><div class="pointer">▼</div><div class="wheelcore">✦</div></div><button class="btn primary big" id="spinbtn" ${s.spins<1?'disabled':''}>SPIN</button><p id="spinmsg">${s.spins?'One free beta spin is ready.':'No spins left today.'}</p></div><div class="card odds"><h3>Possible rewards</h3><div class="rewardlist"><span>5</span><span>10</span><span>25</span><span>50</span><span>100</span><span>JACKPOT</span></div><p>Rewards are experimental beta points with no monetary value.</p></div></div>`);document.getElementById('spinbtn')?.addEventListener('click',doSpin)}
function doSpin(){const s=state();if(s.spins<1)return;s.spins--;save(s);const wheel=document.getElementById('wheel');wheel.classList.add('turn');const vals=[5,10,10,25,25,50,100];const reward=vals[Math.floor(Math.random()*vals.length)];setTimeout(()=>{addReward(reward,'Spin reward');document.getElementById('spinmsg').textContent=`You won +${reward} MAVNARO. Come back tomorrow for another spin.`;document.getElementById('spinbtn').disabled=true},1600)}
function missions(){const list=[['daily-chat','Have 3 conversations','Chat & Earn',15],['first-spin','Use your daily spin','Spin',10],['invite-one','Invite your first friend','Referral',25],['visit-profile','Open your profile','Profile',5]];const s=state();shell('missions',`<div class="grid two">${list.map(m=>`<div class="card mission ${s.completed[m[0]]?'done':''}"><div><span class="missionicon">${s.completed[m[0]]?'✓':'◆'}</span><h3>${m[1]}</h3><p>${m[2]}</p></div><button class="btn" data-m="${m[0]}" data-r="${m[3]}" ${s.completed[m[0]]?'disabled':''}>${s.completed[m[0]]?'Completed':`Claim +${m[3]}`}</button></div>`).join('')}</div><div class="note">Missions are currently local beta demos. In production they will be server-verified.</div>`);document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{const s=state();s.completed[b.dataset.m]=true;save(s);addReward(+b.dataset.r,'Mission reward');missions()})}
function referral(){const s=state();const code='MAV-'+Math.random().toString(36).slice(2,8).toUpperCase();shell('referral',`<div class="refhero card"><span class="pill">YOUR INVITE</span><h2>Bring your people.</h2><p>Share your referral link during beta. Every verified join can unlock bonus points.</p><div class="refbox"><input id="ref" readonly value="https://mavnaro.app/?ref=${code}"><button class="btn primary" id="copy">Copy</button></div><div class="refstats"><div><b>${s.referrals}</b><small>Joined</small></div><div><b>${s.referrals*25}</b><small>Referral points</small></div><div><b>${s.referrals*1}</b><small>Network</small></div></div></div><div class="card"><h3>Referral rules</h3><p>One level only. Production rewards will be issued after server-side verification. No multi-level farming.</p></div>`);document.getElementById('copy').onclick=()=>navigator.clipboard?.writeText(document.getElementById('ref').value).then(()=>document.getElementById('copy').textContent='Copied!')}
function leaderboard(){const names=['NeonRafi','OrbitX','PixelMint','NovaKid','HoodPlayer','Zero404','BlueFox','Questor'];const rows=names.map((n,i)=>({n,score:[8420,7210,6650,5900,5320,4810,4350,3900][i]}));const s=state();rows.push({n:'You',score:s.xp*10});rows.sort((a,b)=>b.score-a.score);shell('leaderboard',`<div class="card table"><div class="cardhead"><h3>Beta leaderboard</h3><span class="pill">LOCAL DEMO</span></div>${rows.map((r,i)=>`<div class="rankrow"><b>#${i+1}</b><span>${r.n}</span><strong>${r.score.toLocaleString()} XP</strong></div>`).join('')}</div><div class="note">Production leaderboard will be server-backed. Demo names are placeholders.</div>`)}
function profile(){const s=state();shell('profile',`<div class="profilegrid"><div class="card profilecard"><div class="profileicon">M</div><h2>Beta Explorer</h2><p>Wallet not connected</p><div class="level"><span>LEVEL ${s.level}</span><b>${s.xp} XP</b></div><div class="bar"><i style="width:${(s.xp%250)/2.5}%"></i></div></div><div class="card"><h3>Activity</h3><div class="row"><span>Chats</span><b>${s.chats}</b></div><div class="row"><span>Referrals</span><b>${s.referrals}</b></div><div class="row"><span>Rewards</span><b>${s.history.length}</b></div><div class="row"><span>Joined</span><b>${new Date(s.joined).toLocaleDateString()}</b></div></div></div><div class="card danger"><h3>Beta controls</h3><p>Reset your local demo account. Production beta resets will be controlled by the server.</p><button class="btn" id="reset">Reset demo</button></div>`);document.getElementById('reset').onclick=()=>{if(confirm('Reset your demo progress?')){localStorage.removeItem(key);profile()}}}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const path=location.pathname.split('/').pop()||'index.html';const page=Object.entries(PAGES).find(([,p])=>p.file===path)?.[0]||'dashboard';({dashboard,chat,spin,missions,referral,leaderboard,profile}[page])();
