/* MAVNARO Beta V2 — static, mobile-first EVM beta. */
const PAGES={dashboard:{title:'Dashboard',sub:'Your MAVNARO beta command center.',file:'index.html'},chat:{title:'Chat & Earn',sub:'Talk, explore, and discover surprise beta rewards.',file:'chat.html'},spin:{title:'Spin',sub:'Take your daily chance at a random beta reward.',file:'spin.html'},missions:{title:'Missions',sub:'Complete activities and build your beta score.',file:'missions.html'},referral:{title:'Referral',sub:'Invite people and track your verified joins.',file:'referral.html'},leaderboard:{title:'Leaderboard',sub:'See the current beta rankings.',file:'leaderboard.html'},profile:{title:'Profile',sub:'Your beta identity, wallet and activity.',file:'profile.html'}};
const icons={dashboard:'⌂',chat:'✦',spin:'◉',missions:'◆',referral:'↗',leaderboard:'♛',profile:'◎'};
const KEY='mavnaro_beta_v2';
const cfg=window.MAVNARO_CONFIG||{};
const today=()=>new Date().toISOString().slice(0,10);
function load(){try{return JSON.parse(localStorage.getItem(KEY))||fresh()}catch{return fresh()}}
function fresh(){const s={balance:0,xp:0,spins:1,spinDate:today(),referrals:0,chats:0,missions:0,streak:0,joined:Date.now(),history:[],completed:{},wallet:null,chainId:null,refCode:null,referrer:null};save(s);return s}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function state(){const s=load();if(s.spinDate!==today()){s.spins=1;s.spinDate=today();save(s)}return s}
function level(xp){return 1+Math.floor(xp/250)}
function addReward(amount,type){const s=state();s.balance+=amount;s.xp+=Math.max(1,Math.floor(amount/2));s.history.unshift({amount,type,time:Date.now()});s.history=s.history.slice(0,50);save(s);return s}
function walletLabel(){const s=state();return s.wallet?s.wallet.slice(0,6)+'…'+s.wallet.slice(-4):'Connect wallet'}
function shell(page,content){document.getElementById('app').innerHTML=`<div class="mobileTop"><a class="brand" href="index.html"><img src="assets/logo.png" alt="MAVNARO"><span>MAVNARO</span></a><button class="iconbtn" id="menuBtn" aria-label="Open menu">☰</button></div><aside class="sidebar" id="sidebar"><div class="sideBrand"><a class="brand" href="index.html"><img src="assets/logo.png" alt="MAVNARO"><span>MAVNARO</span></a><button class="iconbtn close" id="closeMenu">×</button></div><nav>${Object.entries(PAGES).map(([k,p])=>`<a class="nav ${k===page?'active':''}" href="${p.file}"><span>${icons[k]}</span>${p.title}</a>`).join('')}</nav><div class="beta"><b>FREE BETA</b><small>NFT access is OFF during testing. Beta data can be reset.</small></div></aside><div class="backdrop" id="backdrop"></div><main><header><div><div class="eyebrow">MAVNARO / BETA</div><h1>${PAGES[page].title}</h1><p>${PAGES[page].sub}</p></div><button class="walletBtn" id="walletBtn"><span class="dot"></span><span id="walletText">${walletLabel()}</span></button></header><section>${content}</section></main>`;wireShell()}
function wireShell(){document.getElementById('menuBtn')?.addEventListener('click',()=>toggleMenu(true));document.getElementById('closeMenu')?.addEventListener('click',()=>toggleMenu(false));document.getElementById('backdrop')?.addEventListener('click',()=>toggleMenu(false));document.querySelectorAll('.nav').forEach(a=>a.addEventListener('click',()=>toggleMenu(false)));document.getElementById('walletBtn')?.addEventListener('click',connectWallet)}
function toggleMenu(open){document.getElementById('sidebar')?.classList.toggle('open',open);document.getElementById('backdrop')?.classList.toggle('show',open);document.body.classList.toggle('menuOpen',open)}
async function connectWallet(){if(!window.ethereum){toast('No EVM wallet found. Open this page in MetaMask/Coinbase Wallet browser or install a wallet.');return}try{const accounts=await window.ethereum.request({method:'eth_requestAccounts'});if(!accounts?.[0])return;const chain=await window.ethereum.request({method:'eth_chainId'});const s=state();s.wallet=accounts[0];s.chainId=parseInt(chain,16);save(s);renderWallet();toast('Wallet connected: '+accounts[0].slice(0,6)+'…'+accounts[0].slice(-4));}catch(e){toast(e?.message||'Wallet connection cancelled.')}}
function renderWallet(){const s=state();const el=document.getElementById('walletText');if(el)el.textContent=s.wallet?s.wallet.slice(0,6)+'…'+s.wallet.slice(-4):'Connect wallet'}
function watchWallet(){if(!window.ethereum)return;window.ethereum.on?.('accountsChanged',a=>{const s=state();s.wallet=a?.[0]||null;save(s);renderWallet()});window.ethereum.on?.('chainChanged',c=>{const s=state();s.chainId=parseInt(c,16);save(s);renderWallet()})}
function cards(){const s=state();return `<div class="grid stats"><div class="card stat"><small>BETA BALANCE</small><strong>${s.balance.toLocaleString()}</strong><span>MAVNARO POINTS</span></div><div class="card stat"><small>XP</small><strong>${s.xp}</strong><span>Level ${level(s.xp)}</span></div><div class="card stat"><small>REFERRALS</small><strong>${s.referrals}</strong><span>verified joins</span></div><div class="card stat"><small>SPINS</small><strong>${s.spins}</strong><span>available today</span></div></div>`}
function dashboard(){const s=state();shell('dashboard',`${cards()}<div class="hero"><div><span class="pill">SEASON 0 · FREE BETA</span><h2>Enter the experiment.</h2><p>MAVNARO is a social reward playground. Chat, spin, complete missions and invite friends. Beta points have no monetary value and may be reset.</p><div class="actions"><a class="btn primary" href="chat.html">Start chatting</a><a class="btn" href="spin.html">Try your spin</a></div></div><img src="assets/cover.png" alt="MAVNARO world"></div><div class="grid two"><div class="card"><div class="cardhead"><h3>Recent rewards</h3><a href="profile.html">View all</a></div>${s.history.length?s.history.slice(0,6).map(x=>`<div class="row"><span>${x.type}</span><b>+${x.amount}</b></div>`).join(''):'<div class="empty">No rewards yet. Your first one is waiting.</div>'}</div><div class="card"><div class="cardhead"><h3>Beta flow</h3></div><div class="steps"><div><b>01</b><span>Connect</span></div><div><b>02</b><span>Interact</span></div><div><b>03</b><span>Earn points</span></div><div><b>04</b><span>Invite</span></div></div></div></div>`)}
function chat(){shell('chat',`<div class="chatwrap card"><div class="chatlog" id="chatlog"><div class="bubble bot"><span class="avatar">M</span><div><b>MAVNARO</b><p>Welcome to the beta. Start a conversation. Your activity is saved on this device.</p></div></div></div><div class="composer"><input id="chatinput" placeholder="Start a conversation…" maxlength="240" autocomplete="off"><button class="btn primary" id="send">Send</button></div><small class="hint">Beta reward points are experimental. A production AI/reward backend will be connected before Season 1.</small></div>`);document.getElementById('send').onclick=sendChat;document.getElementById('chatinput').onkeydown=e=>{if(e.key==='Enter')sendChat()}}
function sendChat(){const input=document.getElementById('chatinput');const text=input.value.trim();if(!text)return;const log=document.getElementById('chatlog');log.insertAdjacentHTML('beforeend',`<div class="bubble user"><div><p>${escapeHtml(text)}</p></div></div>`);input.value='';const s=state();s.chats++;save(s);if(s.chats>=3&&!s.completed['daily-chat'])missionUnlock('daily-chat');const replies=['Interesting. What would make someone return tomorrow?','That is a useful angle. Push the idea one step further.','MAVNARO noticed that one. Try something more unusual.','What would you change if you had 100,000 users?'];setTimeout(()=>{const reward=Math.min(20,Math.max(3,Math.floor(text.length/20)+3));addReward(reward,'Chat activity');const reply=replies[Math.floor(Math.random()*replies.length)]+` · Beta activity reward: +${reward}.`;log.insertAdjacentHTML('beforeend',`<div class="bubble bot"><span class="avatar">M</span><div><b>MAVNARO</b><p>${reply}</p></div></div>`);log.scrollTop=log.scrollHeight},350)}
function spin(){const s=state();shell('spin',`<div class="spinpage"><div class="card wheelcard"><div class="wheel" id="wheel"><div class="pointer">▼</div><div class="wheelcore">✦</div></div><button class="btn primary big" id="spinbtn" ${s.spins<1?'disabled':''}>SPIN</button><p id="spinmsg">${s.spins?'One free beta spin is ready today.':'Your daily spin is used. Come back tomorrow.'}</p></div><div class="card odds"><h3>Possible beta rewards</h3><div class="rewardlist"><span>5</span><span>10</span><span>25</span><span>50</span><span>100</span><span>JACKPOT</span></div><p>These are beta points only. No monetary value and no on-chain transfer.</p></div></div>`);document.getElementById('spinbtn')?.addEventListener('click',doSpin)}
function doSpin(){const s=state();if(s.spins<1)return;s.spins=0;save(s);const wheel=document.getElementById('wheel');wheel.classList.add('turn');const vals=[5,10,10,25,25,50,100];const reward=vals[Math.floor(Math.random()*vals.length)];setTimeout(()=>{addReward(reward,'Spin reward');document.getElementById('spinmsg').textContent=`You won +${reward} beta points. Your next spin is tomorrow.`;document.getElementById('spinbtn').disabled=true;missionUnlock('first-spin')},1600)}
function missionUnlock(id){const s=state();if(!s.completed[id]){s.completed[id]=true;const map={'daily-chat':15,'first-spin':10};if(map[id])addReward(map[id],'Mission reward');s.missions++;save(s)}}
function missions(){const list=[['daily-chat','Have 3 conversations','Chat & Earn',15,state().chats>=3],['first-spin','Use your daily spin','Spin',10,state().spinDate===today()&&state().spins===0],['invite-one','Invite your first friend','Referral',25,state().referrals>0],['visit-profile','Open your profile','Profile',5,false]];const s=state();shell('missions',`<div class="grid two">${list.map(m=>`<div class="card mission ${s.completed[m[0]]?'done':''}"><div><span class="missionicon">${s.completed[m[0]]?'✓':'◆'}</span><div><h3>${m[1]}</h3><p>${m[2]}</p></div></div><button class="btn" data-m="${m[0]}" data-r="${m[3]}" ${s.completed[m[0]]?'disabled':''}>${s.completed[m[0]]?'Completed':m[4]?`Claim +${m[3]}`:'Locked'}</button></div>`).join('')}</div><div class="note">These beta missions are locally verifiable for testing. Season 1 will use server-side verification.</div>`);document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{if(b.disabled)return;const s=state();s.completed[b.dataset.m]=true;addReward(+b.dataset.r,'Mission reward');s.missions++;save(s);missions()})}
function referral(){const s=state();if(!s.refCode){s.refCode='MAV-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(36).slice(0,7).toUpperCase();save(s)}const base=location.origin+location.pathname.replace(/\/[^/]*$/,'/');const link=base+'?ref='+s.refCode;s.referrer=new URLSearchParams(location.search).get('ref')||s.referrer;save(s);shell('referral',`<div class="refhero card"><span class="pill">YOUR INVITE</span><h2>Bring your people.</h2><p>Share your personal beta link. Referral counters become server-verified in production.</p><div class="refbox"><input id="ref" readonly value="${link}"><button class="btn primary" id="copy">Copy</button></div><div class="refstats"><div><b>${s.referrals}</b><small>Verified joins</small></div><div><b>${s.referrals*25}</b><small>Referral points</small></div><div><b>1 level</b><small>Referral depth</small></div></div></div><div class="card"><h3>Referral rules</h3><p>One level only. Beta referral verification is local; production rewards will require a backend to prevent self-referrals and farming.</p></div>`);document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(document.getElementById('ref').value);document.getElementById('copy').textContent='Copied!'}catch{document.getElementById('ref').select();document.execCommand('copy');document.getElementById('copy').textContent='Copied!'}}}
function leaderboard(){const names=['NeonRafi','OrbitX','PixelMint','NovaKid','HoodPlayer','Zero404','BlueFox','Questor'];const scores=[8420,7210,6650,5900,5320,4810,4350,3900];const s=state();const rows=names.map((n,i)=>({n,score:s.xp*10>scores[i]&&n==='NeonRafi'?scores[i]:scores[i]}));rows.push({n:s.wallet?'You':'You (this device)',score:s.xp*10});rows.sort((a,b)=>b.score-a.score);shell('leaderboard',`<div class="card table"><div class="cardhead"><h3>Beta leaderboard</h3><span class="pill">DEVICE DEMO</span></div>${rows.map((r,i)=>`<div class="rankrow"><b>#${i+1}</b><span>${r.n}</span><strong>${r.score.toLocaleString()} XP</strong></div>`).join('')}</div><div class="note">A real shared leaderboard requires a server/database. This beta version intentionally does not fake shared data.</div>`)}
function profile(){const s=state();shell('profile',`<div class="profilegrid"><div class="card profilecard"><div class="profileicon">✦</div><h2>Beta Explorer</h2><p>${s.wallet?'Wallet connected':'Wallet not connected'}</p><div class="level"><span>LEVEL ${level(s.xp)}</span><b>${s.xp} XP</b></div><div class="bar"><i style="width:${Math.min(100,(s.xp%250)/2.5)}%"></i></div><button class="btn primary full" id="profileWallet">${s.wallet?'Wallet connected':'Connect wallet'}</button></div><div class="card"><h3>Activity</h3><div class="row"><span>Chats</span><b>${s.chats}</b></div><div class="row"><span>Referrals</span><b>${s.referrals}</b></div><div class="row"><span>Rewards</span><b>${s.history.length}</b></div><div class="row"><span>Wallet</span><b>${s.wallet?s.wallet.slice(0,6)+'…'+s.wallet.slice(-4):'—'}</b></div><div class="row"><span>Joined</span><b>${new Date(s.joined).toLocaleDateString()}</b></div></div></div><div class="card danger"><h3>Beta controls</h3><p>Reset only this browser's beta data. It does not touch your wallet or blockchain.</p><button class="btn" id="reset">Reset local beta</button></div>`);document.getElementById('reset').onclick=()=>{if(confirm('Reset local beta progress?')){localStorage.removeItem(KEY);profile()}};document.getElementById('profileWallet').onclick=connectWallet}
function toast(msg){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3200)}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const path=location.pathname.split('/').pop()||'index.html';const page=Object.entries(PAGES).find(([,p])=>p.file===path)?.[0]||'dashboard';({dashboard,chat,spin,missions,referral,leaderboard,profile}[page])();watchWallet();
